# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-29 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('token', models.CharField(max_length=256)),
            ],
        ),
    ]
