# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.4 on 2018-11-12 04:40
=======
# Generated by Django 1.11.4 on 2018-11-09 02:45
>>>>>>> a36aa4bce93d11a07836f67b965861f5ca724ad5
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=0)),
                ('isselect', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('img_l', models.CharField(max_length=100)),
                ('img_r', models.CharField(max_length=100)),
                ('img_d', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('introduce', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('price_p', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'commodity',
            },
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cart')),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> a36aa4bce93d11a07836f67b965861f5ca724ad5
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('token', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'wheel',
            },
        ),
        migrations.AddField(
<<<<<<< HEAD
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
=======
>>>>>>> a36aa4bce93d11a07836f67b965861f5ca724ad5
            model_name='cart',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Commodity'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
