# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wheel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('img_l', models.CharField(max_length=100)),
                ('img_r', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('introduce', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('price_p', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'commodity',
            },
        ),
    ]
